version: '3.7'
services:
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
  postgres-notificator:
    image: postgres:latest
    restart: always
    container_name: notificator-db-container
    environment:
      POSTGRES_DB: ${POSTGRES_NOTIFICATOR_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - ${POSTGRES_NOTIFICATOR_DB_PORT}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
