version: '3'
services:
  eureka:
    restart: always
    image: openjdk:17
    volumes:
      - ${PWD}/eureka-server-0.0.1-SNAPSHOT.jar:/app/eureka.jar
    command: >
      java -XX:MaxRAMPercentage=10.0
           -XX:InitialRAMPercentage=10.0
           -XX:+ExitOnOutOfMemoryError
           -Xmx64m
           -jar /app/eureka.jar
    ports:
      - "8761:8761"
    networks:
      - choosethenews-network
networks:
  choosethenews-network:
    external: true
