version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Pre-build steps...
      - cd user-service
      - ./gradlew clean
  build:
    commands:
      - echo Build of User service started on `date`
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - user-service/build/libs/*.jar

cache:
  paths:
    - '/root/.gradle/caches/**/*'
