version: '3.8'
services:
  user-service:
    build: .
    ports:
      - "8073:8073"
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - USER_DB_NAME
      - POSTGRES_ROOT_PASSWORD
      - JWT_SECRET
      - MAIL_PASSWORD
      - MAIL_TO
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    env_file:
      - .env
    networks:
      - choosethenews-network
networks:
  choosethenews-network:
    external: true