version: '3.8'
services:
  user-service:
    build: .
    ports:
      - "8073:8073"
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - USER_DB_NAME
      - POSTGRES_ROOT_PASSWORD
      - JWT_SECRET
      - MAIL_PASSWORD
      - MAIL_TO
    env_file:
      - .env
