version: 0.0
os: linux
files:
  - source: aggregator-service-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/services/aggregator-service
hooks:
  ApplicationStart:
    - location: start_application.sh
      timeout: 180
      runas: ec2-user
