version: '3.8'
services:
  user-service:
    restart: always
    image: openjdk:17
    volumes:
      - ${PWD}/user-service-0.0.1-SNAPSHOT.jar:/app/user-service.jar
    command: >
      java -XX:MaxRAMPercentage=10.0
           -XX:InitialRAMPercentage=10.0
           -XX:+ExitOnOutOfMemoryError
           -Xmx64m
           -jar /app/user-service.jar
    ports:
      - "8073:8073"
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - USER_DB_NAME
      - POSTGRES_ROOT_PASSWORD
      - JWT_SECRET
      - MAIL_PASSWORD
      - MAIL_TO
    env_file:
      - ../.env
    networks:
      - choosethenews-network
networks:
  choosethenews-network:
    external: true